In [1]:
import pandas as pd


In [2]:
df = pd.read_csv('dataset_social_technical_1d.csv')

In [3]:
df.head()

date  SMA_ratio  SMA_Volume_Ratio  Stochastic_15  Stochastic_Ratio  \
0  02/01/2017   0.977920          0.492545      97.353507          1.120103   
1  03/01/2017   0.980867          0.742189      75.999927          0.982504   
2  04/01/2017   0.986854          0.853517      53.600042          0.811504   
3  05/01/2017   0.999960          1.239421       3.183555          0.595832   
4  06/01/2017   1.013771          1.492017       8.742321          0.412543   

      RSI_15  RSI_ratio      MACD  price_pct_variation  title_vader_compound  \
0  72.819253   1.203449 -0.581692             0.005325              -0.16735   
1  74.418628   0.745917 -0.467702            -0.012655              -0.15890   
2  60.256465   0.399212 -0.265055            -0.016691              -0.17000   
3  45.764364   0.145136  0.161075            -0.043195               0.44040   
4  39.408387   0.153017  0.484190            -0.012355               0.09180   

   title_roberta_neg  title_roberta_neu  title_roberta_pos  
0           0.777352           0.212674           0.009974  
1           0.352967           0.593894           0.053139  
2           0.455775           0.529359           0.014867  
3           0.090196           0.465504           0.444300  
4           0.307789           0.220473           0.471738

In [4]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import  OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

import plotly.express as px
import plotly.graph_objects as go
import plotly.io as pio
# setting Jedha color palette as default
pio.templates["jedha"] = go.layout.Template(
    layout_colorway=["#4B9AC7", "#4BE8E0", "#9DD4F3", "#97FBF6", "#2A7FAF", "#23B1AB", "#0E3449", "#015955"]
)
pio.templates.default = "jedha"
pio.renderers.default = "iframe" # to be replaced by "iframe" if working on JULIE

In [5]:
num_features = df.loc[:, df.columns != 'date'].columns

In [6]:
num_features

Index(['SMA_ratio', 'SMA_Volume_Ratio', 'Stochastic_15', 'Stochastic_Ratio',
       'RSI_15', 'RSI_ratio', 'MACD', 'price_pct_variation',
       'title_vader_compound', 'title_roberta_neg', 'title_roberta_neu',
       'title_roberta_pos'],
      dtype='object')

In [7]:
for sz in num_features:
    print(sz)
    fig = px.histogram(df[sz])
    c = input('')
    fig.show()
    

SMA_ratio


 y


SMA_Volume_Ratio


 y


Stochastic_15


 y


Stochastic_Ratio


 y


RSI_15


 y


RSI_ratio


 y


MACD


 y


price_pct_variation


 y


title_vader_compound


 y


title_roberta_neg


 y


title_roberta_neu


 y


title_roberta_pos


 y


In [8]:
corr_matrix = df.corr().round(2)


In [9]:
import plotly.figure_factory as ff
fig = ff.create_annotated_heatmap(corr_matrix.values,
                                  x = corr_matrix.columns.tolist(),
                                  y = corr_matrix.index.tolist())
fig.show()


In [10]:
features_list = num_features
features_list = ['SMA_ratio', 'Stochastic_15', 'Stochastic_Ratio', 'RSI_15', 'MACD', 'title_vader_compound']

target_variable = ['price_pct_variation']

features_list
target_variable

['price_pct_variation']

In [11]:
features_list

['SMA_ratio',
 'Stochastic_15',
 'Stochastic_Ratio',
 'RSI_15',
 'MACD',
 'title_vader_compound']

In [12]:
target_variable

['price_pct_variation']

In [13]:
X = df.loc[:, features_list]
y = df.loc[:, target_variable]


In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=0)

In [15]:
X_train.head()

SMA_ratio  Stochastic_15  Stochastic_Ratio     RSI_15      MACD  \
333   1.093056       3.846117          0.570785  25.952040  4.105239   
317   0.965982      76.801406          0.797133  68.619795 -2.370400   
974   1.049984      35.245876          0.609594  30.901306  1.468646   
731   0.996851      41.975165          1.423084  42.553159  0.011529   
535   1.046541       6.037731          0.894880  24.189808  1.821725   

     title_vader_compound  
333              0.106067  
317             -0.077200  
974             -0.124390  
731              0.004304  
535              0.040906

In [16]:
y_train.head()

price_pct_variation
333            -0.030194
317            -0.020286
974             0.036319
731            -0.001020
535            -0.056815

In [17]:
X_test.head()

SMA_ratio  Stochastic_15  Stochastic_Ratio     RSI_15      MACD  \
1018   0.987348      62.192823          1.071867  63.079871 -1.070437   
1020   0.998891      33.746557          0.864440  42.403780 -0.580445   
870    1.004748      15.899618          0.257542  49.223950  0.303199   
184    0.978933      66.958697          0.608132  72.610276 -1.258680   
686    0.964942      92.712536          1.084195  84.470949 -2.340089   

      title_vader_compound  
1018             -0.019660  
1020             -0.152736  
870              -0.081838  
184               0.000000  
686               0.070400

In [18]:
y_test.head()

price_pct_variation
1018            -0.003940
1020            -0.013680
870             -0.014930
184             -0.021123
686              0.005501

In [19]:
preprocessor = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])
X_train = preprocessor.fit_transform(X_train)
print(X_train[0:5,:]) # X_train is now a numpy array


[[ 2.8841753  -1.62921137 -1.21190414 -1.46549631  2.8537171   0.45687557]
 [-1.07866467  0.79355821 -0.56223866  0.95523055 -1.60639065 -0.55789348]
 [ 1.54095693 -0.58645789 -1.10051359 -1.18470299  1.03775927 -0.81919005]
 [-0.11600663 -0.36298517  1.23436537 -0.52364277  0.03416697 -0.10659627]
 [ 1.43359269 -1.55643014 -0.28168543 -1.56547538  1.2809425   0.09607469]]


In [20]:
print(X_test.head())
print()
X_test = preprocessor.transform(X_test)

      SMA_ratio  Stochastic_15  Stochastic_Ratio     RSI_15      MACD  \
1018   0.987348      62.192823          1.071867  63.079871 -1.070437   
1020   0.998891      33.746557          0.864440  42.403780 -0.580445   
870    1.004748      15.899618          0.257542  49.223950  0.303199   
184    0.978933      66.958697          0.608132  72.610276 -1.258680   
686    0.964942      92.712536          1.084195  84.470949 -2.340089   

      title_vader_compound  
1018             -0.019660  
1020             -0.152736  
870              -0.081838  
184               0.000000  
686               0.070400  



In [21]:
print(X_test[0:5,:])


[[-0.41236928  0.30842231  0.22630273  0.64092666 -0.71103905 -0.23928775]
 [-0.05240448 -0.63624872 -0.36905598 -0.53211771 -0.37355605 -0.97614719]
 [ 0.1302647  -1.2289271  -2.11097472 -0.14517988  0.23505508 -0.58357719]
 [-0.6747883   0.46669205 -1.10471246  1.18162783 -0.84069159 -0.13042802]
 [-1.11108643  1.32195037  0.26168551  1.8545353  -1.58551388  0.25938505]]


In [22]:
regressor = LinearRegression()
regressor.fit(X_train, y_train)


LinearRegression()

In [23]:
y_train_pred = regressor.predict(X_train)
y_test_pred = regressor.predict(X_test)

In [24]:
print(y_train_pred[0:10])

[[ 0.00270672]
 [ 0.00613149]
 [ 0.01075044]
 [-0.00969953]
 [-0.01133715]
 [-0.00328797]
 [ 0.01805773]
 [ 0.00675913]
 [-0.00514351]
 [-0.01274501]]


In [25]:
print(y_train[0:10])


      price_pct_variation
333             -0.030194
317             -0.020286
974              0.036319
731             -0.001020
535             -0.056815
898              0.003879
311              0.009636
605              0.004392
503             -0.017424
1126            -0.010968


In [26]:
y_test_pred[0:10]

array([[ 0.00144616],
       [-0.00885123],
       [-0.01648829],
       [ 0.00344213],
       [ 0.01159241],
       [-0.00371742],
       [-0.00666423],
       [-0.02269505],
       [-0.00453276],
       [ 0.00888435]])

In [27]:
print(y_test[0:10])

      price_pct_variation
1018            -0.003940
1020            -0.013680
870             -0.014930
184             -0.021123
686              0.005501
938             -0.002834
568             -0.000892
893             -0.020575
431             -0.019575
465              0.026936


In [28]:
print("R2 score on training set : ", r2_score(y_train, y_train_pred))
print("R2 score on test set : ", r2_score(y_test, y_test_pred))


R2 score on training set :  0.28786898513554704
R2 score on test set :  0.30611296542485034
